- hosts: all
  tasks:
  - name: remove files and dirs of all nodes
    file: name={{ item }} state=absent
    with_items:
    - "{{ apps_base_dir }}"
    - "{{ data_base_dir }}"
    - "{{ logs_base_dir }}"
  - name: clean 'ENV PATH'
    lineinfile:
      dest: /etc/profile
      state: absent
      regexp: '{{ item }}'
    with_items:
    - 'ansible_java_home'
    - 'ansible_java_path' 
    - 'ansible_redis_path' 
    