- hosts: all
  tasks:
  - name: remove files and dirs of all nodes
    file: name={{ item }} state=absent
    with_items:
    - "{{ apps_base_dir }}"
    - "{{ data_base_dir }}"
    - "{{ logs_base_dir }}"
    - "/usr/local/mysql/"
   
    
  - name: clean 'ENV PATH'
    lineinfile:
      dest: /etc/profile
      state: absent
      regexp: '{{ item }}'
    with_items:
    - 'ansible_java_home'
    - 'ansible_java_path' 
    - 'ansible_redis_path' 

  - name: clear redis, not active on power on .
    shell: "service redis stop && chkconfig redis off && rm -rf /etc/init.d/redis "

    