#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

### BEGIN INIT INFO
# Provides:     tomcat
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    tomcat
# Description:          tomcat
### END INIT INFO


BASE_DIR="{{ apps_base_dir }}/apache-tomcat-8.5.42/bin/"

case "$1" in
    start)
        echo "111" >> /root/log.log
        echo "111" 
        ps -ef | grep {{ apps_base_dir }}/jdk1.8.0_211 | grep -v grep | awk '{print $2}' | xargs -r kill -9 ;
        echo "222" >> /root/log.log
        echo "222" 
        sleep 5;
        echo "333:${BASE_DIR}startup.sh" >> /root/log.log
        echo "333:${BASE_DIR}startup.sh" 
        ${BASE_DIR}startup.sh 
        echo "444" >> /root/log.log
        echo "444"
        ;;
    stop)
        ps -ef | grep tomcat | grep -v grep | awk '{print $2}' | xargs -r kill -9 ;
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
