- name: remove old mysql data file.
  file: name={{ item }} state=absent
  with_items:
  - "{{ data_base_dir }}/mysql"
  - "{{ logs_base_dir }}/mysql"


- name: add mysql user and mysql group.
  shell: "groupadd mysql && useradd -r -g mysql mysql"

- name: prepare some dirs for mysql
  file: name={{ item }} state=directory owner=mysql group=mysql
  with_items:
  - "/usr/local/mysql/"
  - "{{ data_base_dir }}/mysql"
  - "{{ logs_base_dir }}/mysql"

- name: Extract mysql into {{ apps_base_dir }}
  unarchive:
    src: down/mysql-5.7.26-el7-x86_64.tar.gz
    dest: "/tmp"

- name: movie mysql install file.
  shell: "mv /tmp/mysql-5.7.26-el7-x86_64/* /usr/local/mysql/"

- name: install libaio
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - libaio


- name: set mysql config  script.
  template:
    src: my.cnf
    dest: "/etc/my.cnf"


- name: ./bin/mysqld --initialize --user=mysql --datadir=/apps/data/mysql/.
  shell: "./bin/mysqld --initialize --user=mysql --datadir=/apps/data/mysql/"
  args:
    chdir: "/usr/local/mysql/"

- name: ./bin/mysql_ssl_rsa_setup.
  shell: "./bin/mysql_ssl_rsa_setup"
  args:
    chdir: "/usr/local/mysql/"

- name: update $PATH veriable for java.
  lineinfile:
    dest: /etc/profile
    state: present
    regexp: 'ansible_mysql_path'
    line: 'export PATH=/usr/local/mysql/bin/:$PATH  # generated by ansible_mysql_path'

- name: set mysql start script.
  template:
    src: mysql.server
    dest: "/etc/init.d/mysql"

- name: start mysql .
  shell: "{{ item }}"
  with_items:
  - "chmod +x /etc/init.d/mysql"
  - "chkconfig mysql on"
  - "/etc/init.d/mysql start"

- name: wait for 5 secnods until mysql is actived.
  wait_for: port=3306 delay=5

- name: prepare init sql file.
  template:
    src: init.sql
    dest: "/tmp/init.sql"

- name: run init sql .
  shell: "{{ item }}"
  with_items:
  - "abc=$(cat {{ logs_base_dir }}/mysql/mysqld_error.log|grep 'temporary p' | awk '{print $NF}') && /usr/local/mysql/bin/mysql --connect-expired-password  -uroot -p$abc < /tmp/init.sql "
